### ISSUE TITLE
Make releases page accessible without token when repository is public

### ISSUE THREAD

**Issue by ollyhensby** [ewjoachim/sphinx-github-changelog#70]
So I made my repository public and sphinx doesn't produce my "Releases" page when building due to a token not being given.

However, from my understanding, this isn't necessary any more as the repository is now public so any individual has permission to read the repo?

How my .rst is setup in my docs:

![image](https://user-images.githubusercontent.com/79875276/173808180-383581fd-9237-4a71-aa68-2b5af88dc53f.png)

I've added "sphinx_github_changelog" to my conf.py in extensions.

Missing release information:

![image](https://user-images.githubusercontent.com/79875276/173809321-fe09889e-420e-4b0e-b609-bdaf877bc3b5.png)

Of course, when I add the Github token it works successfully:

![image](https://user-images.githubusercontent.com/79875276/173809940-5110b956-3cec-4565-bbcf-ea3ffb784f31.png)

Any help with this is much appreciated!

Cheers

**Comment by ewjoachim** [comment]
Yes, you're right that in theory, the information is publicly accessible.
The problem is that there are 2 official GH APIs for getting a release: [the REST API](https://docs.github.com/en/rest/releases/releases#get-a-release), and the [GraphQL API](https://docs.github.com/en/graphql/reference/objects#release). The REST API provides the body as a markdown string and can be used authenticated or unauthenticated, and the GraphQL API can only be used with proper authentication, but provides the content in HTML or in Markdown.

Sphinx needs HTML, and trying to make it work from markdown would probably be complicated. Converting the markdown ourselves could be a solution but it's GitHub-Flavored Markdown (GFM) so it's somewhat specific.

That said, there was a solution I didn't think of at the time I created this: GitHub provides a 2nd REST API for [converting GFM into HTML](https://docs.github.com/en/rest/markdown).

We could change the code to use the REST APIs instead of the GraphQL API. there's one important fact: when calling GitHub Rest API unauthenticated, the rate limit it 1. really low (60 requests/hour) and 2. IP-based (which means that when calling from a cloud CI or ReadTheDocs builder or what, chances are at any point, the rate limit stock is already depleted before your first call).
Also, the naive implementation would be 1 call per pagination page for getting the releases themselves, and then 1 call per release for transforming GFM into HTML. Even if you're the only user of the unauthenticated GitHub API, this means that with a project that has, say, 30 releases, your sphinx build will already start failing because of rate limits after the 2nd build in less than an hour.

We could imagine being smarter: putting all the releases in a single payload, transforming that payload from GFM to HTML, and then splitting it again. That means some kind of smart way of parsing the resulting HTML and extraying the different releases. There's probably something smart we could be doing there, but there's no doubt it would make the code much more complicated. And given that it would still frequently fail in ReadTheDocs builder because even a single unauthenticated call is most of the time not even available, I'm not sure there's a lot to gain complexifying the code.

And now that we've explored this venue, I'm wondering what your usecase is so that you wouldn't be able to use a Personal Access Token, even one without any specific permissions and from a dedicated empty account, for your needs ?

**Comment by ollyhensby** [comment]
Thank you for such a thorough response. I don't really understand the technicalities of changing to REST API, however, from what you've written, it does not sound ideal due to the issue with the rate limit.

My original thought was that if a user doesn't have admin rights to the repository, then they cannot create an access token to access the releases and, therefore, cannot build the documentation with the releases information.

Currently in my conf.py I use:

```python
sphinx_github_changelog_token = os.environ.get("GITHUB_TOKEN_CHANGELOG")
```

I don't have the token explicitly within the conf.py and therefore the user has to set the environment variable beforehand which is a bit of a pain but not too cumbersome.

However, if a user forks the repository, they can then create their own personal access token to that forked repository which resolves my issue?

To be honest though, it's not a majorly important use case as I don't expect many users to be building documentation in my repository (other than me and the other admin). I guess I thought because the repository was public, then I could slightly simplify my conf.py by removing the above code.

**Comment by ewjoachim** [comment]
Ah, I think there's a detail that might be clarified: you don't need to have admin access to a public project to list its releases. Any user, even without any kind of permissions on the project, can make the API call to list your public project Releases.

**Comment by ewjoachim** [comment]
> However, if a user forks the repository, they can then create their own personal access token to that forked repository which resolves my issue?

Yes, this is typically how these things work when you want secrets to remain secret :)
Note that you can use a pre-configured link to invite users to create a token with a specific description and some permissions (in this cas, no permission) : https://github.com/settings/tokens/new?description=sphinx-github-changelog%20token%20for%20project%20X (they still have to select the duration they want)

**Comment by ollyhensby** [comment]
Thanks for the information on this. Is much appreciated!

I will close the issue now since this has been resolved.

cheers

**Comment by MiSTeR1995** [comment]
How did you solve this problem? I don’t quite understand how to make the documentation assembly display releases from github. If you create an assembly locally, then everything is displayed, and when I start to assemble on Read the docs, it writes this error **Changelog was not built because sphinx_github_changelog_token parameter is missing in the documentation configuration..** Although I pass the token with the rights to read the repository, and my repository is public

**Comment by ewjoachim** [comment]
How do you pass the token ? (also, please open a dedicated issue)
